[package]
name = "rust-automation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.7"
clap = { version = "4.3.19", features = ["derive"] }
get_if_addrs = "0.5.3"
libc = "0.2.147"
pnet = "0.34.0"
pnet_macros = "0.34.0"
rand = "0.8.5"
