[package]
name = "local_net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
default-net = "0.16.2"
libc = "0.2.147"
net-route = "0.2.5"
netdevice = "0.1.1"
pnet = "0.34.0"

